name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Configure Git user
        run: |
          git config --global user.email "dinuvinethumila@gmail.com"
          git config --global user.name "dinuvinethumila"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Prevents the extraheader error
          submodules: true
          lfs: false

      - name: Install Dependencies
        run: npm install

      - name: Fix Permissions for Evershop CLI
        run: chmod +x ./node_modules/.bin/evershop || true

      - name: Build Application
        run: npm run build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_PLANT_05E894D10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e., PR comments)
          action: "upload"
          app_location: "build"  # Correct folder where the compiled React app is located
          api_location: ""  # API source code path - optional
          output_location: "build"  # This should match the folder where the React app is built

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_PLANT_05E894D10 }}
          action: "close"
